Repository lucaoskaique/entregacao-app, pull requests merged in 2024-05, with the labels that each got.

#29 feat: add issuetemplates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#30 feat: add feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#45 bugfix: add whatsapp link on ButtonWpp
  src/components/Hero.tsx
  src/components/ui/button-wpp-hero.tsx
Labels: bug

#47 42 icone fora do ar em produção
  src/assets/images/brand/logo-dark.svg
  src/assets/images/brand/logo-icon-dark.svg
  src/assets/images/brand/logo-icon-green.svg
  src/assets/images/brand/logo-icon-light.svg
  src/assets/images/brand/logo-light.svg
  src/assets/images/brand/logo-name-dark.svg
  src/assets/images/brand/logo-name-light.svg
  src/assets/images/icons/delivery-car-icon.svg
  src/assets/images/icons/instagram-icon.svg
  src/assets/images/icons/padrinho-help-icon.svg
  src/assets/images/icons/whatsapp-icon.svg
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/components/Icons.tsx
  src/components/Logos.tsx
  src/components/Navbar.tsx
  src/components/ui/button-wpp-hero.tsx
Labels: enhancement

#48 39 atualizar site conforme figma com detalhes novos mobile e dektop
  src/assets/images/brand/logo-dark.svg
  src/assets/images/brand/logo-icon-dark.svg
  src/assets/images/brand/logo-icon-green.svg
  src/assets/images/brand/logo-icon-light.svg
  src/assets/images/brand/logo-light.svg
  src/assets/images/brand/logo-name-dark.svg
  src/assets/images/brand/logo-name-light.svg
  src/assets/images/icons/delivery-car-icon.svg
  src/assets/images/icons/instagram-icon.svg
  src/assets/images/icons/padrinho-help-icon.svg
  src/assets/images/icons/whatsapp-icon.svg
  src/components/About.tsx
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/components/Icons.tsx
  src/components/Logos.tsx
  src/components/Navbar.tsx
  src/components/ui/button-wpp-hero.tsx
Labels: bug, enhancement

#51 Fix branch
  src/assets/images/brand/logo-dark.svg
  src/assets/images/brand/logo-icon-dark.svg
  src/assets/images/brand/logo-icon-green.svg
  src/assets/images/brand/logo-icon-light.svg
  src/assets/images/brand/logo-light.svg
  src/assets/images/brand/logo-name-dark.svg
  src/assets/images/brand/logo-name-light.svg
  src/assets/images/icons/delivery-car-icon.svg
  src/assets/images/icons/instagram-icon.svg
  src/assets/images/icons/padrinho-help-icon.svg
  src/assets/images/icons/whatsapp-icon.svg
  src/components/About.tsx
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/components/Icons.tsx
  src/components/Logos.tsx
  src/components/Navbar.tsx
  src/components/ui/button-wpp-hero.tsx
Labels: bug

#52 Atualizações de componentes e estilos - Kaique/bugfix/fix all problems with tailwind grid
  src/components/About.tsx
  src/components/FAQ.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/components/Navbar.tsx
  tailwind.config.js
Labels: bug

#57 Alterações no texto do mais detalhes
  src/components/ui/hero.tsx
Labels: bug

#60 Kaique/bugfix/add links to wpp and instagram
  src/components/ui/footer.tsx
  src/components/ui/hero.tsx
Labels: bug

#65 Alterações na Estilização da seção about
  src/components/About.tsx
Labels: bug, enhancement

#68 66 corrigir as fontes
  src/App.tsx
  src/components/ui/about.tsx
  src/components/ui/faq.tsx
Labels: bug

#63 62 corrigir estilização de background
  src/assets/images/background-desktop-vector-faq.svg
  src/assets/images/background-vector-about.svg
  src/assets/images/background-vector-hero.svg
  src/components/ui/button-wpp-hero.tsx
  src/components/ui/container.tsx
  src/components/ui/faq.tsx
  src/components/ui/footer.tsx
  src/components/ui/hero.tsx
  src/components/ui/navbar.tsx
  src/components/ui/utils/icons.tsx
  src/components/ui/utils/logos.tsx
  src/styles/app.css
Labels: bug, enhancement

#73 refactor: changed Components directory path
  src/App.tsx
  src/components/Features.tsx
  src/components/HeroCards.tsx
  src/components/HowItWorks.tsx
  src/components/Newsletter.tsx
  src/components/Pricing.tsx
  src/components/Services.tsx
  src/components/Team.tsx
  src/components/Testimonials.tsx
  src/components/avatar.tsx
  src/components/badge.tsx
  src/components/card.tsx
  src/components/dropdown-menu.tsx
  src/components/input.tsx
  src/components/mode-toggle.tsx
  src/components/switch.tsx
  src/components/ui/about/about.tsx
  src/components/ui/faq/components/accordion.tsx
  src/components/ui/faq/faq.tsx
  src/components/ui/footer/footer.tsx
  src/components/ui/header/components/navigation-menu.tsx
  src/components/ui/header/components/sheet.tsx
  src/components/ui/header/components/switchTheme.tsx
  src/components/ui/header/navbar.tsx
  src/components/ui/hero/components/hero-card.tsx
  src/components/ui/hero/hero.tsx
  src/components/ui/scroll-to-top.tsx
  src/components/ui/theme-provider.tsx
  src/components/ui/utils/logos.tsx
  src/main.tsx
Labels: enhancement
